jobs:
  create:
    #image: docker.ouroath.com:4443/docker.io/node:18
    image: node:18
    requires: [~pr, ~commit]
    steps:
      - html: wget https://en.wikipedia.org/wiki/Angkor_Wat -O $SD_ARTIFACTS_DIR/Angkor_Wat.html
      - tgz: tar -czvf $SD_ARTIFACTS_DIR/file.tar.gz $SD_ARTIFACTS_DIR
